### ISSUE TITLE
example confusion around IndexedDb

### ISSUE THREAD

**Issue by cn-johndpope** [Bob-HL/Blazor.WebAPIs#1]
the name of the page IndexedDb has caused me some great confusion.
I can see your example running fine - but when I attempt to merge / cherry pick sample into project - I'm looking to reverse some of the code - and it's blowing up.

namespace Cutec.Blazor.WebAPIs.WebAssemblyDemo.Pages
{
    public partial class IndexedDb : ComponentBase

has this variable name 

  [Inject] private DbContext db { get; set; }

and this class inherits from IndexedDb (but that's specifc to the native sdk library - not the example.

namespace Cutec.Blazor.WebAPIs.WebAssemblyDemo
{
    public class DbContext : IndexedDb

IndexedDb has a razor page - routing / etc - but it's slightly tangled.

please consider refactoring  razor page example to have 
IndexedDb -> IDBPage  > IDBComponent / or IDB just to clearly delineate it from the library.

**Comment by Bob-HL** [comment]
Is [2e33172](https://github.com/Bob-HL/Blazor.WebAPIs/commit/2e33172807ba866c5055a42569331b240f6a2ed6) resolved the issue?

**Comment by cn-johndpope** [comment]
Hi Bob - the problem arose and was resolved by implementing a namespace - thanks for your help.
It turned out I was implementing the methods for program.cs in the wrong sub project. 
All good - thanks for your help.
